---
abstract: 'Automatic text wrapping and reformatting'
author:
  - 'Damian Conway <damian@conway.org>'
build_requires:
  Test::More: '0.88'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Autoformat
requires:
  Carp: '0'
  Exporter: '0'
  Text::Reform: '0'
  Text::Tabs: '0'
  overload: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilb/Text-Autoformat
  repository: https://github.com/neilb/Text-Autoformat.git
version: '1.75'
x_generated_by_perl: v5.28.2
x_serialization_backend: 'YAML::Tiny version 1.73'
